"""init

Revision ID: 01c0edece844
Revises: ab7605922708
Create Date: 2026-01-23 21:32:27.368943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c0edece844'
down_revision: Union[str, Sequence[str], None] = 'ab7605922708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    # ### end Alembic commands ###
