"""init

Revision ID: b2741d177d0a
Revises: e5b079c95c8b
Create Date: 2026-01-23 19:20:55.334981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2741d177d0a'
down_revision: Union[str, Sequence[str], None] = 'e5b079c95c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_tracker', sa.Column('money_spent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_tracker', 'money_spent')
    # ### end Alembic commands ###
